id: P004149
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W18124
  title: ཁྲི་ལྡེ་སྲོང་བཙན་གྱི་ལོ་རྒྱུས་མདོ་ཙམ་བརྗོད་པ།
  author: ''
  volumes:
    f13a6339f1444d48b89ad4ed7c480adc:
      image_group_id: I1KG23839
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
